config/routes.rb
Rails.application.routes.draw do

  namespace :users do
    resources :invoices do
      member do
        get :email
        get :print
      end
    end
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  # Relations
  belongs_to :account
  belongs_to :client
  has_many :items
  has_many :payments

  accepts_nested_attributes_for :items
  accepts_nested_attributes_for :payments

  # Validations
  validates :due_at, presence: true

  # Scope
  default_scope -> { order(created_at: :desc) }
  scope :by_account, ->(account){ where(account: account) } 

  # Public
  def to_s
    "Invoice ##{number.to_s}"
  end

  def status
    if payments.sum(:amount) < total
      if due_at < Date.today
        return :overdue
      else
        return :unpaid
      end
    else
      return :paid
    end
  end

  def is?(status)
    status == self.status
  end

  def sub_total
    items.map(&:total).sum
  end

  def tax
    tax_rate*sub_total
  end

  def total
    (shipping || 0)+sub_total
  end

  def number
    id
  end

  def item_references
    items.map(&:reference)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base

  # Relation
  belongs_to :account
  belongs_to :invoice

  # Validations
  validates_presence_of :product, :description, :quantity, :cost
  validates_numericality_of :discount,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 100,
    only_integer: true

  def total
    (self.quantity*self.cost)*(1-(self.discount/100))
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base

  # Relations
  belongs_to :account
  belongs_to :invoice

  # Validations
  validates :amount, :at, presence: true

end

app/controllers/users/invoices_controller.rb
class Users::InvoicesController < Users::BaseController

  # skip_before_filter :verify_authenticity_token, :only => [:create]
  
  before_action :load_resource, except: [
    :create,
    :index,
    :new
  ]

  before_filter :load_resources, :only => [
    :index,
  ]

  # Must be called after load_recource filter.
  before_filter :check_resource_params, :only => [
    :create,
    :update,
  ]


  def create
    @invoice = Invoice.new invoice_params.except(:shift_ids)
    @invoice.account = current_account

    respond_to do |format|
      if @invoice.save!
        format.html { 
          notify :notice, ::I18n.t('messages.resource.created',
            :type       => Invoice.model_name.human,
            :resource   => @invoice
          )
          render action: :show, id: @invoice 
        }
        format.json {
          render json: @invoice
        }
      else
        format.html { 
          notify_now :error, ::I18n.t('messages.resource.not_valid',
            :type     => Invoice.model_name.human,
            :errors   => @invoice.errors.full_messages.to_sentence
          )
          redirect_to action: :show, controller: :clients, id: invoice_params.slice(:client_id)[:client_id], :status => 422 
        }
        format.json {
          render json: {:error => @invoice.errors.full_messages.to_sentence}, status: 422
        }
      end
    end
  end  

  def email
    InvoiceMailer.email_invoice(@invoice, current_user).deliver_later!
    notify :notice, ::I18n.t('messages.resource.messaged',
      :type       => @invoice.client.email,
      :resource   => @invoice
    )
    redirect_to action: :show, id: @invoice 
  end

  def print
  end

  def update
    @invoice.update_attributes invoice_params
    @invoice.save!

    respond_to do |format|
      format.html { 
        notify :notice, ::I18n.t('messages.resource.updated',
          :type       => Invoice.model_name.human,
          :resource   => @invoice
        )
        render action: :show, id: @invoice 
      }
      format.json {
        render json: @invoice
      }
    end
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique, ActiveRecord::RecordNotSaved => e
    respond_to do |format|
      format.html { 
        notify_now :error, ::I18n.t('messages.resource.not_valid',
          :type     => Invoice.model_name.human,
          :errors   => @invoice.errors.full_messages.to_sentence
        )
        redirect_to action: :show, :status => 422 
      }
      format.json {
        render json: {:error => @invoice.errors.full_messages.to_sentence}, status: 422
      }
    end
  end  

  private


  def invoice_params
    params.require(:invoice).permit(:client_id, :due_at, :tax_rate, :shipping, :order_id, 
      items_attributes: [:product, :reference, :description, :quantity, :cost, :discount, :account_id],
      payments_attributes: [:amount, :reference, :at, :account_id])
  end

end

app/views/layouts/invoice.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    meta[content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"]

    = stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track' => true

  body
    = yield

app/views/layouts/invoice.text.slim
= yield

app/views/users/invoices/_payments.html.slim
br
.row
  .col-xs-12
    h2.page-header
      | Add Payment
    .form-inline
      = form_for @invoice, url: users_invoice_path(@invoice), role: 'form' do |f|
        = f.fields_for :payments, Payment.new do |p| 
          = p.hidden_field :account_id, value: current_account.id
          .form-group
            = p.number_field :amount, required: true, placeholder: 'Amount', class: 'form-control', step: :any
          .form-group
            = p.text_field :reference, required: true, placeholder: 'Payment Reference', class: 'form-control'
          .form-group
            = p.date_field :at, value: Date.today, required: true, class: 'form-control'
        '  
        button.btn.btn-primary.btn-flat type="submit" Submit

app/views/users/invoices/index.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-body
          .table-responsive
            table#invoice-list-table.table.no-margin.table-hover
              thead
                tr
                  th 
                    | Invoice Number
                  th
                    = t 'client'
                  th 
                    = t 'amount'
                  th
              tbody
                - @invoices.each do |i|
                  tr id=users_invoice_path(i)
                    td= i.number
                    td= i.client.name
                    td= number_to_currency i.total
                    td.pull-right
                      - unless i.is?(:unpaid)
                        span.label class=(i.is?(:overdue) ? 'label-danger' : 'label-success')
                          = i.status.to_s.camelize
                      - else
                        span.label.label-warning
                          = i.status.to_s.camelize

app/views/users/invoices/new.html.slim
- client = Client.by_account(current_account).find(params[:client_id])
section.invoice
  = form_for @invoice, url: users_invoices_path, role: 'form' do |f|
    .row
      .col-xs-12
        h2.page-header
          - if current_account.logo.nil?
            i.fa.fa-globe
          - else
            = image_tag current_account.logo, alt: 'logo', size: '25x25'
          |  #{current_account.name}
          small.pull-right
            | Date: #{Date.today}
    .row.invoice-info
      .col-sm-4.invoice-col
        |  From 
        address
          strong
            |  #{current_account.name}
          br
          |  #{current_account.address_line_1}
          br
          |  #{current_account.address_line_2}
          br
          i.fa.fa-phone
          |  - #{current_account.phone}
          br
          i.fa.fa-envelope-o
          |  - #{current_account.email}
          br
          i.fa.fa-briefcase
          |  - #{current_account.business_number}
      .col-sm-4.invoice-col
        |  To 
        = f.hidden_field :client_id, value: params[:client_id]
        address
          strong
            |  #{client.name}
          br
          |  #{client.address_line_1}
          br
          |  #{client.address_line_2}
          br
          i.fa.fa-phone
          |  - #{client.phone}
          br
          i.fa.fa-envelope-o
          |  - #{client.email}
      .col-sm-4.invoice-col
        | Payment Due:
        = f.text_field :due_at, value: Date.today, class: 'form-control'
        br
    = render partial: 'form', locals: {f: f, client: client}

    
    .row.no-print
      .col-xs-12
        = link_to 'Cancel', users_client_path(params[:client_id]), class: 'btn btn-default'
        button.btn.btn-success.pull-right type="submit"
          i.fa.fa-credit-card
          |  Create
.clearfix

app/views/users/invoices/print.html.slim
.wrapper
  section.invoice
    .row
      .col-xs-12
        h2.page-header
          - if @invoice.account.logo.nil?
            i.fa.fa-globe
          - else
            = image_tag @invoice.account.logo, alt: 'logo', size: '50x50'
          |  #{@invoice.account.name}
          small.pull-right
            | Date: #{@invoice.created_at.strftime("%d/%m/%Y")}
    .row.invoice-info
      .col-sm-4.invoice-col
        |  From 
        address
          strong
            |  #{@invoice.account.name}
          br
          |  #{@invoice.account.address_line_1}
          br
          |  #{@invoice.account.address_line_2}
          br
          | Phone: #{@invoice.account.phone}
          br
          | Email: #{@invoice.account.email}
      .col-sm-4.invoice-col
        |  To 
        address
          strong
            |  #{@invoice.client.name}
          br
          |  #{@invoice.client.address_line_1}
          br
          |  #{@invoice.client.address_line_2}
          br
          | Phone: #{@invoice.client.phone}
          br
          | Email: #{@invoice.client.email}
      .col-sm-4.invoice-col
        b
          | Invoice ##{@invoice.number}
        / br
        / br
        / b
        /   | Order ID:
        / |  4F3S8J
        br
        b
          | Payment Due:
        |  #{@invoice.due_at.strftime("%d/%m/%Y")}
        br
        / b
        /   | Account:
        / |  968-34567 
    = render partial: 'items', locals: {invoice: @invoice}

javascript:
  window.print();

app/views/users/invoices/show.html.slim
section.invoice
  .row
    .col-xs-12
      h2.page-header
        - if @invoice.account.logo.nil?
          i.fa.fa-globe
        - else
          = image_tag @invoice.account.logo, alt: 'logo', size: '50x50'
        |  #{@invoice.account.name}
        small.pull-right
          | Date: #{@invoice.created_at.strftime("%d/%m/%Y")}
  .row.invoice-info
    .col-sm-4.invoice-col
      |  From 
      address
        strong
          |  #{@invoice.account.name}
        br
        |  #{@invoice.account.address_line_1}
        br
        |  #{@invoice.account.address_line_2}
        br
        i.fa.fa-phone
        |  - #{@invoice.account.phone}
        br
        i.fa.fa-envelope-o
        |  - #{@invoice.account.email}
        br
        i.fa.fa-briefcase
        |  - #{@invoice.account.business_number}
    .col-sm-4.invoice-col
      |  To 
      address
        strong
          |  #{@invoice.client.name}
        br
        |  #{@invoice.client.address_line_1}
        br
        |  #{@invoice.client.address_line_2}
        br
        i.fa.fa-phone
        |  - #{@invoice.client.phone}
        br
        i.fa.fa-envelope-o
        |  - #{@invoice.client.email}
    .col-sm-4.invoice-col
      b
        | Invoice ##{@invoice.number}
      span.pull-right.label class=(@invoice.is?(:paid)? 'label-success' : (@invoice.is?(:overdue) ? 'label-danger' : 'label-warning'))
        = @invoice.status.to_s.upcase
      br
      b
        | Payment Due: 
      | #{@invoice.due_at.strftime("%d/%m/%Y")}  
        
  = render partial: 'items', locals: {invoice: @invoice}
  
  .row.no-print
    .col-xs-12
      = link_to print_users_invoice_path(@invoice), class: 'btn btn-default pull-right', target: '_blank' do
        i.fa.fa-print
        |  Print
      = link_to email_users_invoice_path(@invoice), class: 'btn btn-default pull-right', style: 'margin-right: 5px;' do 
        i.fa.fa-share
        |  Email

  = render partial: 'payments' unless @invoice.is?(:paid)

.clearfix